spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#  h2:
#    console:
#      enabled: true

  sql:
    init:
      mode: never

  jpa:
    show-sql: true
#    database: postgresql
#    database: h2
    database: mysql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: my-password


  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

logging:
  level:
    root: info
#    org.hibernate.sql: debug
#    org.hibernate.type: debug
#    org.springframework.orm.jpa: debug
#    org.springframework.transaction: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  show-login-endpoint: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

management:
  endpoint:
    health:
      show-details: always

#server:
#  ssl:
#    enabled: true
#    key-store: src/main/resources/mykeystore.p12
#    key-store-password: ${SSL_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: myalias