spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: ${MY_DB_NAME}
    password: ${MY_DB_PASSWORD}

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: never

  jpa:
    show-sql: true
#    database: postgresql
    database: h2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: my-password


#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html

logging:
  level:
    root: info
#    org.hibernate.sql: debug
#    org.hibernate.type: debug
#    org.springframework.orm.jpa: debug
#    org.springframework.transaction: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}
