spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cs4ld0l6l47c73fvn82g-a.oregon-postgres.render.com/mydb_o1aj
    username: ${MY_DB_NAME}
    password: ${MY_DB_PASSWORD}

#  h2:
#    console:
#      enabled: true

  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: my-password


#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html

logging:
  level:
    root: info
    org.hibernate.sql: debug
#    org.hibernate.type: debug
#    org.springframework.orm.jpa: debug
#    org.springframework.transaction: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}
