spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cs4ld0l6l47c73fvn82g-a.oregon-postgres.render.com/mydb_o1aj
    username: mydb_o1aj_user
    password: h1uzCpcHAtAMHGlIx5sEuHJW3CR8nx4o

#  h2:
#    console:
#      enabled: true

  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update

#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
